name: Update pkg.go.dev

on:
  workflow_run:
    workflows: ["Go"]
    types: [completed]

jobs:
  update-pkg-go-dev:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Update pkg.go.dev
        run: |
          ESCAPED_MODULE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          curl -fsSL "https://proxy.golang.org/github.com/$ESCAPED_MODULE/@v/${{ github.event.workflow_run.head_branch }}.info"
